[build]
builder = "nixpacks"

[deploy]
startCommand = "python cron_main.py"
restartPolicyType = "never"

# Cron設定でBotの起動/停止を管理
[cron]
# 日本時間 AM 10:00 に起動 (UTC 01:00)
start = "0 1 * * *"
# 日本時間 AM 2:00 に停止 (UTC 17:00 前日)  
stop = "0 17 * * *"